package compose

import (
	"fmt"
	"os"
	"strings"

	"github.com/ma8el/feat/internal/runtime"
)

// writeInclude renders the generated include document and replaces the file
// when it has changed.
//
// It is what joins a project's repositories into one application. Each entry
// carries its own `project_directory`, so paths inside a repository's Compose
// files resolve against that repository's checkout exactly as they do when the
// user runs Compose there by hand. Listing the same files with `--file` instead
// resolves every relative path against one directory, and the second
// repository's build contexts and bind sources then point into the first
// (ADR-065 evidence 2).
//
// Three things about it are load-bearing:
//
//   - every path is absolute. An include entry resolves a relative `path`
//     against the Compose project directory rather than against the document it
//     is written in, and Compose expands no "~";
//   - the long form is used for every entry, because the short form takes no
//     project directory and the project directory is the whole point;
//   - every scalar is written as a JSON string, which is a valid YAML
//     double-quoted scalar, so no path can turn into YAML syntax.
//
// The file is left alone when its contents already match. Every runtime command
// needs it — a status of a runtime that was never created included — so it is
// written whenever the adapter is built, and rewriting it four times a minute
// per task would be four writes a minute nothing reads differently.
func writeInclude(spec runtime.Spec) error {
	document, err := includeDocument(spec)
	if err != nil {
		return err
	}
	if current, err := os.ReadFile(spec.IncludePath); err == nil && string(current) == string(document) {
		return nil
	}
	return replaceFile(spec.IncludePath, document, "generated Compose include")
}

// includeDocument renders the include document for one task's application.
func includeDocument(spec runtime.Spec) ([]byte, error) {
	if err := spec.Validate(); err != nil {
		return nil, err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by Feat for the application runtime of task %s of project %s.\n",
		spec.Task, spec.Project)
	b.WriteString("#\n")
	b.WriteString("# Do not edit: it is rewritten whenever the task's services are addressed. It is\n")
	b.WriteString("# the whole application, composed of the repositories that bring it. Each entry\n")
	b.WriteString("# carries its own project directory, so paths inside a repository's own Compose\n")
	b.WriteString("# files resolve against that repository's checkout and nothing relative crosses\n")
	b.WriteString("# a repository boundary.\n")

	b.WriteString("include:\n")
	for _, include := range spec.Includes {
		fmt.Fprintf(&b, "  # %s\n", include.Repository)
		b.WriteString("  - path:\n")
		for _, file := range include.Files {
			fmt.Fprintf(&b, "      - %s\n", quote(file))
		}
		fmt.Fprintf(&b, "    project_directory: %s\n", quote(include.Directory))
	}
	return []byte(b.String()), nil
}
