package compose

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/ma8el/feat/internal/runtime"
)

// Ownership labels applied to every resource of a task's runtime.
//
// They make what a task owns discoverable without reading any persistent state,
// which is how a later reconciliation resolves it and how this slice lists a
// task's networks and volumes. The kind label separates an application service
// from the agent's own container: both are Feat's, and only one of them is the
// environment the user is testing.
const (
	LabelOwner   = "dev.feat.owner"
	LabelProject = "dev.feat.project"
	LabelTask    = "dev.feat.task"
	LabelKind    = "dev.feat.kind"
	LabelSchema  = "dev.feat.schema"

	// OwnerValue marks a resource as Feat's own.
	OwnerValue = "feat"
	// KindValue marks a resource as an application runtime rather than an agent
	// execution environment.
	KindValue = "runtime"
	// SchemaValue is the version of the generated override's shape.
	SchemaValue = "1"
)

// File modes for the generated override.
//
// It lives under the state directory, is never mounted anywhere, and is read
// only by Docker Compose running as the user who owns the daemon.
const (
	overrideDirPerm  fs.FileMode = 0o700
	overrideFilePerm fs.FileMode = 0o600
)

// writeOverride renders the generated override and replaces the file
// atomically.
func writeOverride(spec runtime.Spec) error {
	document, err := overrideDocument(spec)
	if err != nil {
		return err
	}

	dir := filepath.Dir(spec.OverridePath)
	if err := os.MkdirAll(dir, overrideDirPerm); err != nil {
		return fmt.Errorf("creating %s for the generated Compose override: %w", dir, err)
	}

	temp, err := os.CreateTemp(dir, "."+filepath.Base(spec.OverridePath)+".tmp-*")
	if err != nil {
		return fmt.Errorf("creating a temporary file in %s: %w", dir, err)
	}
	defer func() { _ = os.Remove(temp.Name()) }()

	if err := temp.Chmod(overrideFilePerm); err != nil {
		return fmt.Errorf("setting permissions on %s: %w", temp.Name(), err)
	}
	if _, err := temp.Write(document); err != nil {
		return fmt.Errorf("writing %s: %w", temp.Name(), err)
	}
	if err := temp.Close(); err != nil {
		return fmt.Errorf("closing %s: %w", temp.Name(), err)
	}
	if err := os.Rename(temp.Name(), spec.OverridePath); err != nil {
		return fmt.Errorf("replacing %s: %w", spec.OverridePath, err)
	}
	return nil
}

// overrideDocument renders the Compose override for one task's application.
//
// Four things about it are load-bearing rather than stylistic, and each is
// pinned by a test:
//
//   - every mount uses the long form, so a path containing a colon is a value
//     rather than a syntax error waiting to happen;
//   - every scalar is written as a JSON string, which is a valid YAML
//     double-quoted scalar, so no path, name, or generated value can turn into
//     YAML syntax;
//   - container_name is reset. It is global to the Docker daemon, so a base file
//     carrying one could be brought up for exactly one task, and one task per
//     machine is not the product;
//   - published ports are left exactly as the project configured them. They are
//     how the user reaches the application they are testing, and v0 allocates
//     none of its own; two tasks wanting the same host port is explained rather
//     than silently prevented (ADR-034).
//
// It is generated text and never carries a value read from an environment file,
// because nothing that reads one ever reaches this function.
func overrideDocument(spec runtime.Spec) ([]byte, error) {
	if err := spec.Validate(); err != nil {
		return nil, err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by Feat for the application runtime of task %s of project %s.\n",
		spec.Task, spec.Project)
	b.WriteString("#\n")
	b.WriteString("# Do not edit: it is rewritten every time the task's services are created or\n")
	b.WriteString("# started, and it is merged last over the project's own Compose files. Compose\n")
	b.WriteString("# merges a service's volumes by target, so each mount below replaces whatever\n")
	b.WriteString("# the base files mounted at that path rather than adding a second mount beside\n")
	b.WriteString("# it.\n")
	b.WriteString("#\n")
	b.WriteString("# container_name is reset because it is global to the Docker daemon: a base file\n")
	b.WriteString("# carrying one could be started for one task and no more. Published ports are\n")
	b.WriteString("# left as configured, because they are how you reach the application.\n")

	b.WriteString("services:\n")
	for _, service := range spec.Services {
		fmt.Fprintf(&b, "  %s:\n", quote(service))
		b.WriteString("    container_name: !reset null\n")

		if len(spec.Mounts) > 0 {
			b.WriteString("    volumes:\n")
			for _, mount := range spec.Mounts {
				if mount.Description != "" {
					fmt.Fprintf(&b, "      # %s\n", mount.Description)
				}
				fmt.Fprintf(&b, "      - type: %s\n", quote("bind"))
				fmt.Fprintf(&b, "        source: %s\n", quote(mount.Source))
				fmt.Fprintf(&b, "        target: %s\n", quote(mount.Target))
				fmt.Fprintf(&b, "        read_only: %t\n", mount.ReadOnly)
			}
		}

		if entries := spec.Entries(); len(entries) > 0 {
			b.WriteString("    environment:\n")
			for _, entry := range entries {
				fmt.Fprintf(&b, "      %s: %s\n", quote(entry[0]), quote(entry[1]))
			}
		}

		b.WriteString("    labels:\n")
		for _, label := range [][2]string{
			{LabelOwner, OwnerValue},
			{LabelProject, spec.Project.String()},
			{LabelTask, spec.Task.String()},
			{LabelKind, KindValue},
			{LabelSchema, SchemaValue},
		} {
			fmt.Fprintf(&b, "      %s: %s\n", quote(label[0]), quote(label[1]))
		}
	}
	return []byte(b.String()), nil
}

// quote renders a value as a YAML double-quoted scalar.
//
// YAML 1.2 is a superset of JSON and its double-quoted scalars use JSON's
// escaping, so a JSON string is a correct YAML scalar. Doing it this way means
// no path, name, or generated value can be read as YAML syntax, and the rule is
// one function rather than a habit each call site has to remember.
func quote(value string) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		// json.Marshal fails for a string only on invalid UTF-8, which every
		// caller's value has already been validated against.
		return `""`
	}
	return string(encoded)
}
