package claude

import (
	"fmt"
	"strings"
)

// Claude hook event names, verified against the installed Claude Code
// (see version.go for the range this build was checked against).
const (
	hookSessionStart     = "SessionStart"
	hookUserPromptSubmit = "UserPromptSubmit"
	hookStop             = "Stop"
	hookStopFailure      = "StopFailure"
	hookNotification     = "Notification"
	hookSessionEnd       = "SessionEnd"
)

// hookFileName is the generated script for one event.
func hookFileName(event string) string {
	var b strings.Builder
	for i, r := range event {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('-')
			}
			r += 'a' - 'A'
		}
		b.WriteRune(r)
	}
	return b.String() + ".sh"
}

// hookScript renders the script installed for one hook event.
//
// The script does one thing: it writes what Claude gave it into the control
// outbox, atomically, and exits. It parses nothing, because parsing a provider's
// payload belongs in this package's Go code where it can be tested, and it
// interprets nothing, because a hook that decided what an event meant would be
// a second normalizer nobody could see.
//
// Two properties are not stylistic and are pinned by a test:
//
//   - it writes nothing to standard output. Claude injects a UserPromptSubmit
//     hook's standard output into the model's context, so an echo here would
//     silently put Feat's own words into the user's conversation;
//   - it always exits 0. A Stop hook exiting 2 blocks the agent, so a hook that
//     failed on a full disk would stop the session it exists to observe.
//
// Both mean the same thing: this script observes a session and must never
// change it.
func hookScript(event, task, outbox string) string {
	return fmt.Sprintf(`#!/bin/sh
# Generated by Feat for task %[1]s, hook %[2]s. Do not edit: it is rewritten
# every time the task's session is launched.
#
# It copies the hook payload into the control outbox and does nothing else.
# Two rules keep it from changing the session it observes:
#
#   - nothing is written to standard output. Claude injects a UserPromptSubmit
#     hook's standard output into the model's context.
#   - the exit status is always 0. A Stop hook exiting 2 blocks the agent.
#
# Everything below therefore discards its own errors and gives up quietly: a
# hook that cannot report is a dashboard that is briefly out of date, while a
# hook that fails loudly is a session that stops.
set -u

outbox=%[3]s
task=%[1]s
hook=%[2]s

staging=$(mktemp "$outbox/.feat-XXXXXXXXXX" 2>/dev/null) || exit 0
base=${staging##*/}
# The staging name is dot-prefixed so that a reader ignores it until it is
# complete; the message name is the same identifier without the dot.
id=${base#.}
stamp=$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ 2>/dev/null) || stamp=1970-01-01T00:00:00Z

{
  printf '{"schema_version":1,"id":"%%s","task_id":"%%s","type":"provider_event","occurred_at":"%%s","payload":{"hook":"%%s","event":' \
    "$id" "$task" "$stamp" "$hook"
  cat
  printf '}}\n'
} >"$staging" 2>/dev/null || {
  rm -f "$staging" 2>/dev/null
  exit 0
}

mv "$staging" "$outbox/$id.json" 2>/dev/null || rm -f "$staging" 2>/dev/null
exit 0
`, task, event, shellQuote(outbox))
}

// reportOptions are the values the generated helper is built from.
type reportOptions struct {
	// task is the task the helper reports for.
	task string
	// outbox and inbox are the message directories, as the agent sees them.
	outbox string
	inbox  string
	// gate reports that a completion gate will answer a review request, so the
	// helper waits for the verdict rather than returning at once.
	gate bool
	// publication reports that this task has somewhere to publish, so the
	// helper accepts a publication draft. A project with no forge configured
	// never sees the type (ADR-070).
	publication bool
	// acknowledge and verdict are the two waits, in whole seconds.
	acknowledge int
	verdict     int
}

// reportScript renders the helper the agent runs to post a message.
//
// It exists so that an agent-authored message is written atomically and in the
// right shape. Unlike a hook, it is run deliberately by the agent as a command,
// so it reports what it did and fails loudly when it is misused: the agent is
// the one who needs to know that its review request did not land.
//
// It executes nothing it is given. The body is read as data, wrapped in an
// envelope, and written to a file; the daemon validates and applies it later.
// No control message ever executes shell text (docs/05-security-model.md).
//
// When the project configures checks, this is also where a failed gate reaches
// the agent: the helper waits for the daemon's verdict and exits non-zero with
// the failing output on standard error, so the model reads a failed tool call
// and carries on in the same turn. That is why the gate hangs off the helper
// rather than off a hook — a hook that blocked would be a hook that changes the
// session it observes, and Claude's only blocking hook fires at the end of every
// turn rather than when review is requested (ADR-036).
//
// A check that never ran is the one verdict that does not come back as a failed
// command, because it is not this session's to fix and the loop has nowhere to
// take it (ADR-055).
func reportScript(opts reportOptions) string {
	script := fmt.Sprintf(`#!/bin/sh
# Generated by Feat for task %[1]s. Do not edit: it is rewritten every time the
# task's session is launched.
#
# Usage: feat-report <type> < body.json
#
#   review_requested   the work is ready for a human to review
#   completion_report  an account of what was done
#   open_question      you are blocked on a decision only the user can make
%[3]s#
# The body is read as data and never executed. Feat validates it and decides
# what it means; this script only puts it in the outbox atomically.
set -u

outbox=%[2]s
task=%[1]s

type=${1:-}
case "$type" in
  %[4]s) ;;
  *)
    echo "usage: feat-report {%[4]s} < body.json" >&2
    exit 2
    ;;
esac

staging=$(mktemp "$outbox/.feat-XXXXXXXXXX") || {
  echo "feat-report: could not write to $outbox" >&2
  exit 1
}
base=${staging##*/}
id=${base#.}
stamp=$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ 2>/dev/null) || stamp=1970-01-01T00:00:00Z

{
  printf '{"schema_version":1,"id":"%%s","task_id":"%%s","type":"%%s","occurred_at":"%%s","payload":' \
    "$id" "$task" "$type" "$stamp"
  cat
  printf '}\n'
} >"$staging" || {
  rm -f "$staging"
  echo "feat-report: could not write the message" >&2
  exit 1
}

mv "$staging" "$outbox/$id.json" || {
  rm -f "$staging"
  echo "feat-report: could not deliver the message" >&2
  exit 1
}
echo "feat-report: recorded $type as $id"
`, opts.task, shellQuote(opts.outbox), publicationUsage(opts), acceptedTypes(opts))

	if !opts.gate {
		return script + "exit 0\n"
	}
	return script + fmt.Sprintf(`
# A completion gate is configured for this task, so a review request is answered
# rather than merely recorded. Feat runs the project's checks itself and writes
# the verdict here; this script waits for it and exits non-zero when a check
# failed, so the result reaches you as a failed command rather than as a message
# nobody read.
if [ "$type" != review_requested ]; then
  exit 0
fi

inbox=%[1]s
verdict="$inbox/verification-$id.txt"

echo "feat-report: waiting for the project's checks"

# First that Feat has the request at all. A daemon that is not running must not
# leave this waiting for an hour.
waited=0
while [ ! -f "$verdict" ]; do
  if [ "$waited" -ge %[2]d ]; then
    echo "feat-report: Feat did not acknowledge the request within %[2]ds; the review request stands and the dashboard will show what happened"
    exit 0
  fi
  sleep 1
  waited=$((waited + 1))
done

# Then for the answer. The first line is "feat-verification <version> <status>",
# which is three fields and no parsing.
waited=0
while :; do
  format=; version=; status=
  { read -r format version status || true; } <"$verdict"
  if [ "$format" != feat-verification ] || [ "$version" != 1 ]; then
    echo "feat-report: Feat wrote a verdict this session does not understand; see the dashboard"
    exit 0
  fi
  case "$status" in
    accepted)
      if [ "$waited" -ge %[3]d ]; then
        echo "feat-report: the checks did not finish within %[3]ds; the dashboard will show what happened"
        exit 0
      fi
      sleep 2
      waited=$((waited + 2))
      ;;
    passed|skipped)
      tail -n +2 "$verdict"
      exit 0
      ;;
    failed)
      echo "feat-report: the project's checks did not pass. The work is not ready for review yet." >&2
      tail -n +2 "$verdict" >&2
      exit 1
      ;;
    blocked)
      # Deliberately not a failed command. A check that never ran says nothing
      # about the work, and it is the project's configuration or environment
      # rather than anything this session can fix, so it goes to the user
      # instead of back into the loop (ADR-055).
      echo "feat-report: Feat could not run the project's checks and has told the user."
      tail -n +2 "$verdict"
      exit 0
      ;;
    *)
      echo "feat-report: Feat reported the status '$status', which this session does not understand"
      exit 0
      ;;
  esac
done
`, shellQuote(opts.inbox), opts.acknowledge, opts.verdict)
}

// acceptedTypes renders the message types the helper accepts, in the order the
// usage line lists them.
//
// A project with no forge configured never sees publication_draft: a type the
// helper would accept and Feat would have nowhere to send is an invitation to
// write a document nobody reads (ADR-070).
func acceptedTypes(opts reportOptions) string {
	types := []string{"review_requested", "completion_report", "open_question"}
	if opts.publication {
		types = append(types, "publication_draft")
	}
	return strings.Join(types, "|")
}

// publicationUsage is the helper's own comment about the draft, or nothing.
func publicationUsage(opts reportOptions) string {
	if !opts.publication {
		return ""
	}
	return "#   publication_draft  the merge request you propose for each repository\n"
}
