package claude

import (
	"fmt"
	"strings"
)

// Claude hook event names, verified against the installed Claude Code
// (see version.go for the range this build was checked against).
const (
	hookSessionStart     = "SessionStart"
	hookUserPromptSubmit = "UserPromptSubmit"
	hookStop             = "Stop"
	hookStopFailure      = "StopFailure"
	hookNotification     = "Notification"
	hookSessionEnd       = "SessionEnd"
)

// hookFileName is the generated script for one event.
func hookFileName(event string) string {
	var b strings.Builder
	for i, r := range event {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('-')
			}
			r += 'a' - 'A'
		}
		b.WriteRune(r)
	}
	return b.String() + ".sh"
}

// hookScript renders the script installed for one hook event.
//
// The script does one thing: it writes what Claude gave it into the control
// outbox, atomically, and exits. It parses nothing, because parsing a provider's
// payload belongs in this package's Go code where it can be tested, and it
// interprets nothing, because a hook that decided what an event meant would be
// a second normalizer nobody could see.
//
// Two properties are not stylistic and are pinned by a test:
//
//   - it writes nothing to standard output. Claude injects a UserPromptSubmit
//     hook's standard output into the model's context, so an echo here would
//     silently put Feat's own words into the user's conversation;
//   - it always exits 0. A Stop hook exiting 2 blocks the agent, so a hook that
//     failed on a full disk would stop the session it exists to observe.
//
// Both mean the same thing: this script observes a session and must never
// change it.
func hookScript(event, task, outbox string) string {
	return fmt.Sprintf(`#!/bin/sh
# Generated by Feat for task %[1]s, hook %[2]s. Do not edit: it is rewritten
# every time the task's session is launched.
#
# It copies the hook payload into the control outbox and does nothing else.
# Two rules keep it from changing the session it observes:
#
#   - nothing is written to standard output. Claude injects a UserPromptSubmit
#     hook's standard output into the model's context.
#   - the exit status is always 0. A Stop hook exiting 2 blocks the agent.
#
# Everything below therefore discards its own errors and gives up quietly: a
# hook that cannot report is a dashboard that is briefly out of date, while a
# hook that fails loudly is a session that stops.
set -u

outbox=%[3]s
task=%[1]s
hook=%[2]s

staging=$(mktemp "$outbox/.feat-XXXXXXXXXX" 2>/dev/null) || exit 0
base=${staging##*/}
# The staging name is dot-prefixed so that a reader ignores it until it is
# complete; the message name is the same identifier without the dot.
id=${base#.}
stamp=$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ 2>/dev/null) || stamp=1970-01-01T00:00:00Z

{
  printf '{"schema_version":1,"id":"%%s","task_id":"%%s","type":"provider_event","occurred_at":"%%s","payload":{"hook":"%%s","event":' \
    "$id" "$task" "$stamp" "$hook"
  cat
  printf '}}\n'
} >"$staging" 2>/dev/null || {
  rm -f "$staging" 2>/dev/null
  exit 0
}

mv "$staging" "$outbox/$id.json" 2>/dev/null || rm -f "$staging" 2>/dev/null
exit 0
`, task, event, shellQuote(outbox))
}

// reportScript renders the helper the agent runs to post a message.
//
// It exists so that an agent-authored message is written atomically and in the
// right shape. Unlike a hook, it is run deliberately by the agent as a command,
// so it reports what it did and fails loudly when it is misused: the agent is
// the one who needs to know that its review request did not land.
//
// It executes nothing it is given. The body is read as data, wrapped in an
// envelope, and written to a file; the daemon validates and applies it later.
// No control message ever executes shell text (docs/05-security-model.md).
func reportScript(task, outbox string) string {
	return fmt.Sprintf(`#!/bin/sh
# Generated by Feat for task %[1]s. Do not edit: it is rewritten every time the
# task's session is launched.
#
# Usage: feat-report <type> < body.json
#
#   review_requested   the work is ready for a human to review
#   completion_report  an account of what was done
#   open_question      you are blocked on a decision only the user can make
#
# The body is read as data and never executed. Feat validates it and decides
# what it means; this script only puts it in the outbox atomically.
set -u

outbox=%[2]s
task=%[1]s

type=${1:-}
case "$type" in
  review_requested|completion_report|open_question) ;;
  *)
    echo "usage: feat-report {review_requested|completion_report|open_question} < body.json" >&2
    exit 2
    ;;
esac

staging=$(mktemp "$outbox/.feat-XXXXXXXXXX") || {
  echo "feat-report: could not write to $outbox" >&2
  exit 1
}
base=${staging##*/}
id=${base#.}
stamp=$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ 2>/dev/null) || stamp=1970-01-01T00:00:00Z

{
  printf '{"schema_version":1,"id":"%%s","task_id":"%%s","type":"%%s","occurred_at":"%%s","payload":' \
    "$id" "$task" "$type" "$stamp"
  cat
  printf '}\n'
} >"$staging" || {
  rm -f "$staging"
  echo "feat-report: could not write the message" >&2
  exit 1
}

mv "$staging" "$outbox/$id.json" || {
  rm -f "$staging"
  echo "feat-report: could not deliver the message" >&2
  exit 1
}
echo "feat-report: recorded $type as $id"
exit 0
`, task, shellQuote(outbox))
}
