package compose

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/ma8el/feat/internal/execution"
)

// Ownership labels applied to the agent's container.
//
// They are what makes a task's container discoverable without reading any
// persistent state, which is how `feat doctor` finds one to probe inside
// without a daemon and how slice 12 will resolve what a task owns. The schema
// label exists so a later version can recognise a container this one created.
const (
	LabelOwner   = "dev.feat.owner"
	LabelProject = "dev.feat.project"
	LabelTask    = "dev.feat.task"
	LabelSchema  = "dev.feat.schema"

	// OwnerValue marks a resource as Feat's own.
	OwnerValue = "feat"
	// SchemaValue is the version of the generated override's shape.
	SchemaValue = "1"
)

// File modes for the generated override.
//
// It lives under the state directory beside the task's snapshot and is read
// only by Docker Compose, running as the user who owns the daemon.
const (
	overrideDirPerm  fs.FileMode = 0o700
	overrideFilePerm fs.FileMode = 0o600
)

// writeOverride renders the generated override and replaces the file atomically.
func writeOverride(spec execution.Spec) error {
	document, err := overrideDocument(spec)
	if err != nil {
		return err
	}

	dir := filepath.Dir(spec.OverridePath)
	if err := os.MkdirAll(dir, overrideDirPerm); err != nil {
		return fmt.Errorf("creating %s for the generated Compose override: %w", dir, err)
	}

	temp, err := os.CreateTemp(dir, "."+filepath.Base(spec.OverridePath)+".tmp-*")
	if err != nil {
		return fmt.Errorf("creating a temporary file in %s: %w", dir, err)
	}
	defer func() { _ = os.Remove(temp.Name()) }()

	if err := temp.Chmod(overrideFilePerm); err != nil {
		return fmt.Errorf("setting permissions on %s: %w", temp.Name(), err)
	}
	if _, err := temp.Write(document); err != nil {
		return fmt.Errorf("writing %s: %w", temp.Name(), err)
	}
	if err := temp.Close(); err != nil {
		return fmt.Errorf("closing %s: %w", temp.Name(), err)
	}
	if err := os.Rename(temp.Name(), spec.OverridePath); err != nil {
		return fmt.Errorf("replacing %s: %w", spec.OverridePath, err)
	}
	return nil
}

// overrideDocument renders the Compose override for one task.
//
// Three things about it are load-bearing rather than stylistic, and each is
// pinned by a test:
//
//   - every mount uses the long form, so a path containing a colon is a value
//     rather than a syntax error waiting to happen;
//   - every scalar is written as a JSON string, which is a valid YAML
//     double-quoted scalar, so no path or name can turn into YAML syntax;
//   - container_name and ports are reset. Both are global — a container name to
//     the Docker daemon, a published port to the host — so a base file carrying
//     either could be started exactly once, and one task per machine is not the
//     product (ADR-033).
//
// It is generated text and never carries a value read from an environment file,
// because nothing that reads one ever reaches this function.
func overrideDocument(spec execution.Spec) ([]byte, error) {
	if err := spec.Validate(); err != nil {
		return nil, err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by Feat for task %s of project %s.\n", spec.Task, spec.Project)
	b.WriteString("#\n")
	b.WriteString("# Do not edit: it is rewritten every time the task's environment starts, and\n")
	b.WriteString("# it is merged last over the project's own Compose files. Compose merges a\n")
	b.WriteString("# service's volumes by target, so each mount below replaces whatever the base\n")
	b.WriteString("# files mounted at that path rather than adding a second mount beside it.\n")
	b.WriteString("#\n")
	b.WriteString("# container_name and ports are reset because both are global: a container name\n")
	b.WriteString("# to the Docker daemon and a published port to the host. A base file carrying\n")
	b.WriteString("# either could run for one task and no more.\n")

	b.WriteString("services:\n")
	fmt.Fprintf(&b, "  %s:\n", quote(spec.Service))
	b.WriteString("    container_name: !reset null\n")
	b.WriteString("    ports: !reset []\n")
	fmt.Fprintf(&b, "    working_dir: %s\n", quote(spec.WorkingDirectory))

	b.WriteString("    volumes:\n")
	for _, mount := range spec.Mounts {
		if mount.Description != "" {
			fmt.Fprintf(&b, "      # %s\n", mount.Description)
		}
		fmt.Fprintf(&b, "      - type: %s\n", quote("bind"))
		fmt.Fprintf(&b, "        source: %s\n", quote(mount.Source))
		fmt.Fprintf(&b, "        target: %s\n", quote(mount.Target))
		fmt.Fprintf(&b, "        read_only: %t\n", mount.ReadOnly)
	}
	for _, volume := range spec.Volumes {
		fmt.Fprintf(&b, "      - type: %s\n", quote("volume"))
		fmt.Fprintf(&b, "        source: %s\n", quote(volume.Name))
		fmt.Fprintf(&b, "        target: %s\n", quote(volume.Target))
		fmt.Fprintf(&b, "        read_only: %t\n", volume.ReadOnly)
	}

	if entries := spec.Entries(); len(entries) > 0 {
		b.WriteString("    environment:\n")
		for _, entry := range entries {
			name, value, _ := strings.Cut(entry, "=")
			fmt.Fprintf(&b, "      %s: %s\n", quote(name), quote(value))
		}
	}

	b.WriteString("    labels:\n")
	for _, label := range []struct{ name, value string }{
		{LabelOwner, OwnerValue},
		{LabelProject, spec.Project.String()},
		{LabelTask, spec.Task.String()},
		{LabelSchema, SchemaValue},
	} {
		fmt.Fprintf(&b, "      %s: %s\n", quote(label.name), quote(label.value))
	}

	if len(spec.Volumes) > 0 {
		b.WriteString("volumes:\n")
		for _, volume := range spec.Volumes {
			// The explicit name keeps Compose from prefixing it with this
			// task's project name. The volume is deliberately shared: one
			// interactive provider login rather than one per task
			// (docs/05-security-model.md, OQ-007).
			fmt.Fprintf(&b, "  %s:\n", quote(volume.Name))
			fmt.Fprintf(&b, "    name: %s\n", quote(volume.Name))
		}
	}
	return []byte(b.String()), nil
}

// quote renders a value as a YAML double-quoted scalar.
//
// YAML 1.2 is a superset of JSON and its double-quoted scalars use JSON's
// escaping, so a JSON string is a correct YAML scalar. Doing it this way means
// no path, name, or generated value can be read as YAML syntax, and the rule is
// one function rather than a habit each call site has to remember.
func quote(value string) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		// json.Marshal fails for a string only on invalid UTF-8, which every
		// caller's value has already been validated against.
		return `""`
	}
	return string(encoded)
}
